export class Dummy {
  val = {
    'blockSpace': 0,
    'bookingId': 0,
    'origin': 'SIN',
    'densityGroupCode': 1,
    'destination': 'HKG',
    'flagDelete': 'string',
    'flagDeletePart': 'string',
    'flagInsert': 'Y',
    'grossWeight': 500,
    'manual': 0,
    'pieces': 200,
    'serviceFlag': 0,
    'shipmentNumber': '000-2222',
    'shipperCustomerId': 0,
    'volumeWeight': 0,
    'weightUnitCode': 'K',
    'natureOfGoods': 'VAL',
    'partBookingList': [{
      'partBookingId': 0,
      'specialHandlingCode2': '',
      'specialHandlingCode3': '',
      'specialHandlingCode4': '',
      'specialHandlingCode5': '',
      'specialHandlingCode6': '',
      'specialHandlingCode7': '',
      'specialHandlingCode8': '',
      'specialHandlingCode9': '',
      'mergeSelect': '',
      'workingListRemarks': '',
      'manifestRemarks': '',
      'additionalRemarks': '',
      'bookingId': 0,
      'partPieces': 120,
      'partSuffix': 'P',
      'partWeight': 200.0,
      'shc1': 'BIG',
      'partIdentifier': 'Y',
      'specialHandlingCode1': 'BIG',
      'shipmentPartBookingDimensionList': [{
        'checkBoxFlag': false,
        'weight': '',
        'flightBookingId': 0,
        'height': 10,
        'length': 20,
        'pieces': 20,
        'width': 40,
        'weightUnitCode': 'K',
        'weightUnit': '',
        'shipmentUnitCode': 'K'
      }, {
        'checkBoxFlag': false,
        'weight': '',
        'flightBookingId': 0,
        'height': 5,
        'length': 5,
        'pieces': 5,
        'width': 5,
        'weightUnitCode': 'L',
        'weightUnit': '',
        'shipmentUnitCode': 'K'
      }],
      'singleShipmentFlightBookingList': [{
          'arrivalTime': 0,
          'weight': '',
          'weightUnit': '',
          'bookingCancellationFlag': 0,
          'bookingCancellationReasonCode': '',
          'bookingCancellationUserCode': '',
          'bookingId': 0,
          'bookingPieces': 120,
          'bookingStatusCode': 'SS',
          'bookingWeight': 200.0,
          'departureTime': 0,
          'flagDelete': 'string',
          'flagInsert': 'string',
          'flagSaved': 'string',
          'flagUpdate': 'string',
          'flightBoardPoint': 'SIN',
          'flightBookingId': 0,
          'flightId': 2535111,
          'flightOffPoint': 'BKK',
          'specialHandlingCode1': 'BIG'
        },
        {
          'arrivalTime': 0,
          'weight': '',
          'weightUnit': '',
          'bookingCancellationFlag': 0,
          'bookingCancellationReasonCode': '',
          'bookingCancellationUserCode': '',
          'bookingId': 0,
          'bookingPieces': 120,
          'bookingStatusCode': 'SS',
          'bookingWeight': 200.0,
          'departureTime': 0,
          'flagDelete': 'string',
          'flagInsert': 'string',
          'flagSaved': 'string',
          'flagUpdate': 'string',
          'flightBoardPoint': 'BKK',
          'flightBookingId': 0,
          'flightId': 2535330,
          'flightOffPoint': 'HKG',
          'specialHandlingCode1': 'BIG'
        }
      ]
    }, {
      'partBookingId': 0,
      'specialHandlingCode2': '',
      'specialHandlingCode3': '',
      'specialHandlingCode4': '',
      'specialHandlingCode5': '',
      'specialHandlingCode6': '',
      'specialHandlingCode7': '',
      'specialHandlingCode8': '',
      'specialHandlingCode9': '',
      'mergeSelect': '',
      'workingListRemarks': '',
      'manifestRemarks': '',
      'additionalRemarks': '',
      'bookingId': 0,
      'partPieces': 80,
      'partSuffix': 'A',
      'partWeight': 300.0,
      'shc1': 'BIG',
      'partIdentifier': 'Y',
      'specialHandlingCode1': 'BIG',
      'shipmentPartBookingDimensionList': [{
        'checkBoxFlag': false,
        'weight': '',
        'weightUnit': '',
        'flightBookingId': 0,
        'height': 40,
        'length': 40,
        'pieces': 40,
        'width': 40,
        'weightUnitCode': 'L',
        'shipmentUnitCode': 'L'
      }, {
        'checkBoxFlag': false,
        'weight': '',
        'weightUnit': '',
        'flightBookingId': 0,
        'height': 10,
        'length': 40,
        'pieces': 40,
        'width': 40,
        'weightUnitCode': 'K',
        'shipmentUnitCode': 'K'
      }],
      'singleShipmentFlightBookingList': [{
          'arrivalTime': 0,
          'bookingCancellationFlag': 0,
          'bookingCancellationReasonCode': '',
          'bookingCancellationUserCode': '',
          'bookingId': 0,
          'bookingPieces': 80,
          'bookingStatusCode': 'SS',
          'bookingWeight': 300.0,
          'departureTime': 0,
          'flagDelete': 'string',
          'flagInsert': 'string',
          'flagSaved': 'string',
          'flagUpdate': 'string',
          'flightBoardPoint': 'SIN',
          'flightBookingId': 0,
          'flightId': 2535111,
          'flightOffPoint': 'BKK',
          'shc1': 'BIG'
        },
        {
          'arrivalTime': 0,
          'bookingCancellationFlag': 0,
          'bookingCancellationReasonCode': '',
          'bookingCancellationUserCode': '',
          'bookingId': 0,
          'bookingPieces': 80,
          'bookingStatusCode': 'SS',
          'bookingWeight': 300.0,
          'departureTime': 0,
          'flagDelete': 'string',
          'flagInsert': 'string',
          'flagSaved': 'string',
          'flagUpdate': 'string',
          'flightBoardPoint': 'HKG',
          'flightBookingId': 0,
          'flightId': 2535330,
          'flightOffPoint': 'BKK',
          'shc1': 'BIG'
        }
      ]
    }]
  };

  // private primaryBookingInformation = {
  //   shipmentNumber: null,
  //   origin:
  // }
  private eachPartBooking = {
    mergeSelect: false,
    partPieces: '',
    partWeight: '',
    workingListRemarks: '',
    manifestRemarks: '',
    additionalRemarks: '',
    'specialHandlingCode1': '',
    'specialHandlingCode2': '',
    'specialHandlingCode3': '',
    'specialHandlingCode4': '',
    'specialHandlingCode5': '',
    'specialHandlingCode6': '',
    'specialHandlingCode7': '',
    'specialHandlingCode8': '',
    'specialHandlingCode9': '',
    'throughTransitFlag': 0,
    shipmentPartBookingDimensionList: [],
    singleShipmentFlightBookingList: [],
    // flagCreatePart: 'Y',
    flagInsert: 'Y',
    flagMergePart: 'N',
    flagDeletePart: 'N',
    updateFlag: 'N',
    // partBookingId: null,
    // bookingId: null,
    // partSuffix: null,
    // 'loggedInUser': null,
    // 'createdBy': null,
    // 'createdOn': null,
    // 'modifiedBy': null,
    // 'modifiedOn': null,
    // 'flagUpdate': 'N',
    // 'flagDelete': 'N',
    // 'flagInsert': 'N',
    // 'flagSaved': 'N',
    // 'sortOrder': {
    //   'sortField': null,
    //   'previousSortField': null
    // },
    // 'paginationContext': {
    //   'currPageIndex': 0,
    //   'nextPageIndex': 0,
    //   'skipResults': 0,
    //   'maxResults': 10,
    //   'moreData': false,
    //   'paginationMode': false,
    //   'listSize': 0,
    //   'pageCount': null
    // },
    // 'totalRowCount': null,
    // 'localDateFormat': null,
    // 'locale': null
  };

  private eachFlightRow = {
    flagInsert: 'Y',
    bookingPieces: 20,
    bookingWeight: 50,
    flightId: '',
    flightBoardPoint: '',
    flightOffPoint: '',
    bookingStatusCode: '',
    arrivalTime: '',
    departureTime: '',
    specialHandlingCode1: '',
    specialHandlingCode2: '',
    specialHandlingCode3: '',
    specialHandlingCode4: '',
    specialHandlingCode5: '',
    specialHandlingCode6: '',
    specialHandlingCode7: '',
    specialHandlingCode8: '',
    specialHandlingCode9: '',
  };

  private eachDimensionRow = {
    'checkBoxFlag': true,
    flagInsert: 'Y',
    'weight': '',
    'weightUnit': '',
    'length': '',
    'width': '',
    'height': '',
    'shipmentUnitCode': '',
    'pieces': '',
    // 'partBookingId': 56,
    // 'txSequenceNumber': 0,
    // 'loggedInUser': null,
    // 'createdBy': null,
    // 'createdOn': null,
    // 'modifiedBy': null,
    // 'modifiedOn': null,
    // 'flagUpdate': 'N',
    // 'flagDelete': 'N',
    // 'flagInsert': 'N',
    // 'flagSaved': 'Y',
    // 'sortOrder': {
    //   'sortField': null,
    //   'previousSortField': null
    // },
    // 'paginationContext': {
    //   'currPageIndex': 0,
    //   'nextPageIndex': 0,
    //   'skipResults': 0,
    //   'maxResults': 10,
    //   'moreData': false,
    //   'paginationMode': false,
    //   'listSize': 0,
    //   'pageCount': null
    // },
    // 'totalRowCount': null,
    // 'localDateFormat': null,
    // 'locale': null,
    // 'messageList': []
  };
  // private mainForm = new NgcFormGroup({
  //   mainScreenList: new NgcFormArray([])
  // });
  // private tabForm = new NgcFormGroup({
  //   tabScreenList: new NgcFormArray([])
  // });
}

