# Server
server:
  servlet:
    context-path: /cosys
  error:
    whitelabel:
      enabled: true

# JMX
spring:
  jmx:
    default-domain: ${spring.application.name}
    enabled: false
    
# Actuator
management:
  endpoint:
    health:
      enabled: true
      show-details: always
    info:
      enabled: true
    loggers:
      enabled: true
    metrics:
      enabled: true
  endpoints:
    web:
      base-path: /actuator/
      exposure:
        include: '*'
  
# Discovery Configuration

##############################################################################################################

eureka:
  client:
    enabled: false
    region: default
    serviceUrl:
      defaultZone: http://discovery.local:9020/eureka/
    
##############################################################################################################
 
   
#
# Profile 'qa'
#
---
spring:
  profiles: qa
eureka:
  client:
    enabled: false
    
#
# Profile 'uat'
#
---
spring:
  profiles: uat
eureka:
  client:
    enabled: true

#
# Profile 'trg'
#
---
spring:
  profiles: trg
eureka:
  client:
    enabled: false

#
# Profile 'stg'
#
---
spring:
  profiles: stg
eureka:
  client:
    enabled: true
    
#
# Profile 'prod'
#
---
spring:
  profiles: prod
eureka:
  client:
    enabled: true
      